# Generated by Django 2.0.2 on 2018-08-05 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='emplist',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('age', models.SmallIntegerField()),
                ('birth', models.DateTimeField()),
                ('gender', models.SmallIntegerField()),
                ('salary', models.FloatField()),
            ],
            options={
                'db_table': 't_emplist',
            },
        ),
    ]
