# Generated by Django 2.0.2 on 2018-08-16 20:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='emplist',
            name='hpic',
            field=models.ImageField(default=22, upload_to='pics'),
            preserve_default=False,
        ),
    ]
