# Generated by Django 2.0.2 on 2018-08-06 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Admins',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=20)),
                ('realname', models.CharField(max_length=20)),
                ('passwd', models.CharField(max_length=20)),
                ('age', models.SmallIntegerField()),
                ('gender', models.SmallIntegerField()),
                ('birth', models.DateTimeField()),
            ],
            options={
                'db_table': 't_admin',
            },
        ),
    ]
