# Generated by Django 2.0.2 on 2018-08-16 20:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admins', '0002_admins_hpic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='admins',
            name='hpic',
            field=models.ImageField(upload_to='pics'),
        ),
    ]
